GET http://localhost:3001/register/
Token: 5OHPXGHNR33LBALF
###

GET http://localhost:3001/register/21

###

DELETE http://localhost:3001/register/21

###

POST http://localhost:3001/register/
Content-Type: application/json

{
  "raquet":3,
  "date": "2022-08-03 15:00",
  "desc": "aaaaa",
  "hours": 2,
  "result": 1,
  "cost": 0
}
            

###

PATCH http://localhost:3001/register/21
Content-Type: application/json 

{
  "raquet":2,
  "date": "2022-07-01 09:00",
  "desc": "svv",
  "hours": 1.5,
  "result": 1,
  "cost": 0
}