GET http://localhost:3001/stringing/

###

GET http://localhost:3001/stringing/7

###

DELETE http://localhost:3001/stringing/5

###

POST http://localhost:3001/stringing/
Content-Type: application/json

{
  "raquet":2,
  "date": "2022-07-03 15:00",
  "strings": "Test",
  "weight": 22,
  "place": "ciccio"
}
            

###

PATCH http://localhost:3001/stringing/7
Content-Type: application/json 

{
  "raquet":1,
  "date": "2022-08-03 15:00",
  "strings": "Test0pppppp",
  "weight": 23,
  "place": "cicsdqfefcio"
}